import { Space_Mono as SpaceMono } from 'next/font/google'
import { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import './globals.css'

const spaceMono = SpaceMono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--space-mono',
})

export const metadata: Metadata = {
  title: 'devFinder',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`${spaceMono.className} font-space-mono`}>
      <body>{children}</body>
    </html>
  )
}
